### ISSUE TITLE
Possible to run without fail file?

### ISSUE THREAD

**Issue by monkpit** [Updater/protractor-fail-fast#13]
I would like to use this plugin in the following scenario...

I have one long end-to-end test that should fail fast. I also have several small, quick tests that should always run. They are in different spec files, so if I run them in parallel, I do not want the small, quick tests to stop if the end-to-end test fails.

From what I gather from the readme, this would be possible by not creating the "fail file" when running in parallel.

Any suggestions to achieve the behavior I need?

**Comment by pmowrer** [comment]
This library wraps [`jasmine-fail-fast`](https://github.com/Updater/jasmine-fail-fast) to add the specific behavior that it appears you're **not** looking for. You might try using `jasmine-fail-fast` directly. You'd probably have to adapt it to the `protractor` plugin format like this library does: 

https://github.com/Updater/protractor-fail-fast/blob/master/src/index.js#L28
