### ISSUE TITLE
chore: Release `bug/cjs-default-export` on npm

### ISSUE THREAD

**Issue by sigv** [Updater/protractor-fail-fast#8]
We use `protractor-fail-fast` and like to keep all our packages up to date. The v3 bump is not working for us but testing with the latest revision of `master` works fine. That begs the question: How come the package is not updated on npm? Could a v3.0.1 be pushed there with the fix that was already merged on `master` earlier? We can't be the only ones suffering from this. 😉

**Comment by pmowrer** [comment]
Thanks for the feedback @sigv! Releasing `v3.0.1` entirely slipped my mind.

**Comment by pmowrer** [comment]
`v3.0.1` has been released! Please note the updated [usage](https://github.com/Updater/protractor-fail-fast#usage). Let me know if you encounter any problems!

**Comment by sigv** [comment]
All working just fine. Thanks! :+1:
